#!/usr/bin/env node

var fs = require('fs'),
    path = require('path'),
    truthy_falsy_values,
    i, length,
    result={},
    result_filepath;

truthy_falsy_values = {
  "true": true,
  "zero": 0,
  "empty_string": "",
  "false": false,
  "[]": [],
  "{}": {},
  "whitespace": " ",
  "None": "-",
  "null": null,
  "nil": "-",
  "NaN": NaN,
  "undefined": undefined
};

for(var key in truthy_falsy_values) {
  if(truthy_falsy_values.hasOwnProperty(key)) {
    var value = truthy_falsy_values[key];

    if(value == "-") {
      result[key] = "-";
    }
    else {
      if(value) {
        result[key] = "Truthy";
      }
      else {
        result[key] = "Falsy";
      }
    }
  }
}

result_filepath = path.join(__dirname, 'result.json');

fs.writeFileSync(result_filepath, JSON.stringify(result));
