#!/usr/bin/env python

import os
import json

truthy_falsy_values = {
  "true": True,
  "zero": 0,
  "empty_string": "",
  "false": False,
  "[]": [],
  "{}": {},
  "whitespace": " ",
  "None": None,
  "null": "-",
  "nil": "-",
  "NaN": "-",
  "undefined": "-"
}

result = {}

for key in truthy_falsy_values:
  val = truthy_falsy_values[key]
  if val == "-":
      result[key] = "-"
  else:
    if val:
        result[key] = "Truthy"
    else:
        result[key] = "Falsy"

result_file = open(os.path.join(os.path.dirname(__file__), 'result.json'), "w")
result_file.write(json.dumps(result))
