#!/usr/bin/env ruby

require 'json'

truthy_falsy_values = {
  "true": true,
  "zero": 0,
  "empty_string": "",
  "whitespace": " ",
  "false": false,
  "nil": nil,
  "[]": [],
  "{}": {}
}

result = {}

truthy_falsy_values.each do |key, value|
  if value
    result[key] = "Truthy"
  else
    result[key] = "Falsy"
  end
end

result_file_path = File.expand_path("../result.json", __FILE__)

File.write(result_file_path, JSON.dump(result))
