#!/usr/bin/env ruby

require 'json'

truthy_falsy_values = {
  "true": true,
  "zero": 0,
  "empty_string": "",
  "false": false,
  "[]": [],
  "{}": {},
  "whitespace": " ",
  "None": "-",
  "null": "-",
  "nil": nil,
  "NaN": "-",
  "undefined": "-"
}

result = {}

truthy_falsy_values.each do |key, value|
  if value == "-"
    result[key] = "-"
  else
    if value
      result[key] = "Truthy"
    else
      result[key] = "Falsy"
    end
  end
end

result_file_path = File.expand_path("../result.json", __FILE__)

File.write(result_file_path, JSON.dump(result))
